version: '3'

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRESQL_URL: jdbc:postgresql://db:5432/codeforge
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
    depends_on:
      - db
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_URL: backend
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: codeforge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      