spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/codeforge'
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
#    properties:
#      hibernate.format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: 'roezrjeoijROrjeOJrojgreogkeropGJeroijGREOjreojORIJGergRJerioJERiogjEORIgiojGOEIJej23FOjIOJwfioRJeklgkrjekjERKGJerkljerklgjeKERLJkljGErklerjKLERjGergKLERjklregl'
  expiration: 15000000
  refreshToken:
    expiration: 120000000
