spring:
  datasource:
    url: ${POSTGRESQL_URL:jdbc:postgresql://localhost:5432/codeforge}
    username: ${POSTGRESQL_USERNAME:postgres}
    password: ${POSTGRESQL_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: 'roezrjeoijROrjeOJrojgreogkeropGJeroijGREOjreojORIJGergRJerioJERiogjEORIgiojGOEIJej23FOjIOJwfioRJeklgkrjekjERKGJerkljerklgjeKERLJkljGErklerjKLERjGergKLERjklregl'
  expiration: 1500000000
  refreshToken:
    expiration: 1200000000
